version: "3.8"

services:
  app:
    image: outline-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: outline-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./uploads:/uploads
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: outline-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: outline
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
